### ISSUE TITLE
Privilegios de instalación de herramientas de desarrollo

### ISSUE THREAD

**Issue by JJ** [jcgq/MII_CC_UGR#69]
Hay una regla que repito sobre lo de arriba. ¿Cuál es y de qué forma se aplicaría a esto?

https://github.com/jcgq/MII_CC_UGR/blob/532eff89598f7d631e6edb21d2311d1dcdacd6f3/README.md?plain=1#L40

**Comment by jcgq** [comment]
Buenas profesor. Ahora le pregunto en clase, pues no logro entender a qué se refiere.

**Comment by jcgq** [comment]
Un desarrollador no puede instalar ni descargar nada con permisos de SUPER usuario. Por tanto, lo corrijo y correctamente lo cambio.
