### ISSUE TITLE
No estás usando Receta

### ISSUE THREAD

**Issue by JJ** [jcgq/MII_CC_UGR#73]
Todo lo que estás usando son funciones, sin crear ningún objeto `Receta`

https://github.com/jcgq/MII_CC_UGR/blob/861caec834f9cf4ef1f148b2d352dbd0dbbeb5cc/test/test.py#L3

**Comment by jcgq** [comment]
Elimino ese import (error mio por hacer copia y pega de las librerías en los archivos) o hago un test de creación de Receta?

**Comment by jcgq** [comment]
Bueno... ahora que lo pienso es algo que quizás deba pensar yo :)
