### ISSUE TITLE
Las buenas prácticas de Python en 2021 ya no incluyen requirements.txt

### ISSUE THREAD

**Issue by JJ** [jcgq/MII_CC_UGR#83]
Ni, por tanto, pip

https://github.com/jcgq/MII_CC_UGR/blob/ce45a10c3dae0d19bd901004310187b978bd15be/Dockerfile#L24

**Comment by jcgq** [comment]
De acuerdo. Gracias por el comentario. Lo trabajaré durante esta tarde.
